// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkeVuIiVifiNdfEYElXuX4p3dbyIVft38',
    appId: '1:79409894722:web:59b1966d6259a581d5e4db',
    messagingSenderId: '79409894722',
    projectId: 'doctor-appointment-bf73a',
    authDomain: 'doctor-appointment-bf73a.firebaseapp.com',
    storageBucket: 'doctor-appointment-bf73a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWjvLrVP-G66E45gZl_j064To3esPuzA',
    appId: '1:79409894722:android:62f069fa2299d527d5e4db',
    messagingSenderId: '79409894722',
    projectId: 'doctor-appointment-bf73a',
    storageBucket: 'doctor-appointment-bf73a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsiwx7hkPV4Fz9LXbArD-ilKQf5kGev0E',
    appId: '1:79409894722:ios:bcece9bb3bc84ffad5e4db',
    messagingSenderId: '79409894722',
    projectId: 'doctor-appointment-bf73a',
    storageBucket: 'doctor-appointment-bf73a.appspot.com',
    iosClientId: '79409894722-vag8qdd6mb5c475nr2tcumie0j1reduj.apps.googleusercontent.com',
    iosBundleId: 'com.dlovan.hestinn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsiwx7hkPV4Fz9LXbArD-ilKQf5kGev0E',
    appId: '1:79409894722:ios:bcece9bb3bc84ffad5e4db',
    messagingSenderId: '79409894722',
    projectId: 'doctor-appointment-bf73a',
    storageBucket: 'doctor-appointment-bf73a.appspot.com',
    iosClientId: '79409894722-vag8qdd6mb5c475nr2tcumie0j1reduj.apps.googleusercontent.com',
    iosBundleId: 'com.dlovan.hestinn',
  );
}
